---
- name: Register status of target archive path
  ansible.builtin.stat:
    path: "{{ target_backup_directory }}/{{ docker_compose_stack_name }}.tar.gz"
  register: backup_archive_status

- name: Create backup of docker directory
  when: not backup_archive_status.stat.exists
  block:
    - name: Stop the docker compose stack
      community.docker.docker_compose_v2:
        project_src: "{{ docker_compose_stack_path }}"
        state: absent

    - name: Create an archive of the docker compose stack
      community.general.archive:
        path: "{{ docker_compose_stack_path }}"
        dest: "{{ target_backup_directory }}/{{ docker_compose_stack_name }}.tar.gz"
        mode: "0644"
        owner: pstet
        group: pstet
  always:
    - name: Start the docker compose stack
      community.docker.docker_compose_v2:
        project_src: "{{ docker_compose_stack_path }}"
        state: present
