---
- name: Wake up the backup server
  hosts: localhost
  any_errors_fatal: true
  tasks:
    - name: Send wake on lan packet to the backup server
      community.general.wakeonlan:
        mac: "{{ backup_server_mac }}"
      changed_when: false

    - name: Wait for server connection
      ansible.builtin.wait_for_connection:
        delay: 10
        timeout: 120
      delegate_to: "{{ borg_host }}"

- name: Execute backups on all homelab hosts
  hosts: appservers
  become: true
  tasks:
    - name: Ensure the backup script is up-to-date
      ansible.builtin.template:
        src: borgbackup.sh.j2
        dest: "{{ client_backup_script_path }}"
        owner: root
        group: root
        mode: "0700"

    - name: Run the backup script
      ansible.builtin.command: "{{ client_backup_script_path }}"
      throttle: 1

- name: Retrieve borg info and shut down
  hosts: backup
  become: true
  tasks:
    - name: Retrieve borg stats
      borg_stats:
        pool_path: "/home/borg/repos"
        clients: "{{ groups['servers'] + groups['pis'] }}"
      environment:
        BORG_PASSPHRASE: "{{ borg_passphrase }}"
      register: borg_stats
      become: true

    - name: Place borg stats in a json file
      ansible.builtin.copy:
        content: "{{ borg_stats.stats }}"
        dest: "/srv/docker/nginx/content/borg.json" # TODO: This needs to be changed to a variable
        mode: "0755"
      delegate_to: nixon.pcstet.home

    - name: Shut down the system
      community.general.shutdown:
