---
- name: Initial setup for each homelab device for use with ansible
  hosts: homelab
  become: true
  remote_user: pstet
  tasks:
    - name: Add ansible user
      ansible.builtin.user:
        name: ansible
        shell: /bin/bash
        create_home: true
        state: present

    - name: Ensure ansible user has sudo permissions
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/ansible
        line: "ansible ALL=(ALL) NOPASSWD: ALL"
        mode: "0600"
        owner: root
        group: root
        state: present
        create: true

    - name: Ensure pstet user has public key
      ansible.posix.authorized_key:
        user: pstet
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
        state: present

    - name: Ensure ansible user has public key
      ansible.posix.authorized_key:
        user: ansible
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
        state: present
